version: "3.9"

services:
  arbwiz_es:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
      container_name: arbwiz_es
      environment:
        - node.name=es01
        - cluster.name=es-docker
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - ingest.geoip.downloader.enabled=false
        - action.destructive_requires_name=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200